version: "3.9"

services:
  database_sofit: 
    image: postgres
    container_name: db_sofit
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=sofit
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: sofit
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database_sofit
    depends_on:
      - database_sofit

volumes:
  pgdata:
    driver: local
